const API=localStorage.getItem("marg_api")||window.MARG_API_URL||"http://localhost:4000", token=()=>localStorage.getItem("marg_admin_token");
async function req(path,options={}){options.headers={...(options.headers||{}),Authorization:"Bearer "+token(),"Content-Type":"application/json"};const r=await fetch(API+path,options);const d=await r.json();if(!r.ok)throw Error(d.error||"Request failed");return d}
const form=document.querySelector("#adminLogin");
if(form)form.onsubmit=async e=>{e.preventDefault();try{const r=await fetch(API+"/api/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:email.value,password:password.value})});const d=await r.json();if(!r.ok)throw Error(d.error||"Login failed");if(d.user.role!=="ADMIN")throw Error("This account is not an administrator.");localStorage.setItem("marg_admin_token",d.token);location.href="admin-dashboard.html"}catch(x){msg.textContent=x.message}};
if(location.pathname.endsWith("admin-dashboard.html")){if(!token())location.href="admin-login.html";else init()}
async function init(){try{const me=await req("/api/me");if(me.user.role!=="ADMIN")throw Error("Administrator account required");who.textContent=me.user.name;await Promise.all([loadStats(),loadTravellers(),loadProviders(),loadServices(),loadBookings(),loadSos()])}catch(e){alert(e.message);localStorage.removeItem("marg_admin_token");location.href="admin-login.html"}}
async function loadStats(){const d=await req("/api/admin/stats");statTravellers.textContent=d.stats.travellers;statProviders.textContent=d.stats.providers;statServices.textContent=`${d.stats.publishedServices}/${d.stats.services}`;statBookings.textContent=d.stats.bookings;statSos.textContent=d.stats.activeSos;statPending.textContent=d.stats.pendingProviders}
async function loadTravellers(){const d=await req("/api/admin/users?role=TRAVELER");travellerRows.innerHTML=d.users.map(u=>`<tr><td>${esc(u.name)}</td><td>${esc(u.email)}</td><td>${esc(u.phone||"—")}</td><td>${new Date(u.createdAt).toLocaleDateString()}</td><td><span class="status">Active</span></td></tr>`).join("")||emptyRow(5)}
async function loadProviders(){const d=await req("/api/admin/users?role=VENDOR");providerCards.innerHTML=d.users.map(u=>`<article class="admin-card"><div><span class="badge provider-badge">SERVICE PROVIDER</span><h3>${esc(u.name)}</h3><p>${esc(u.email)} · ${esc(u.phone||"No phone")}</p><p>${u.services.length} service(s) · ${u.services.filter(s=>s.published).length} published</p></div><div class="card-actions"><span class="status">${u.providerApproved?"Approved":"Pending"}</span>${!u.providerApproved?`<button class="btn provider-btn" onclick="approve('${u.id}')">Approve</button>`:""} </div></article>`).join("")||"<p>No service providers registered.</p>"}
async function approve(id){try{await req("/api/admin/providers/"+id+"/approve",{method:"POST",body:"{}"});loadStats();loadProviders()}catch(e){alert(e.message)}}
async function loadServices(){const d=await req("/api/admin/services");serviceRows.innerHTML=d.services.map(s=>`<tr><td><b>${esc(s.name)}</b></td><td>${s.category}</td><td>${esc(s.provider.name)}</td><td>${esc(s.destination)}</td><td>${money(s.priceMinor,s.currency)}</td><td><span class="status">${s.published?"Published":"Draft"}</span></td></tr>`).join("")||emptyRow(6)}
async function loadBookings(){const d=await req("/api/admin/bookings");bookingRows.innerHTML=d.bookings.map(b=>`<tr><td>${esc(b.id.slice(0,10))}</td><td>${esc(b.user.name)}</td><td>${esc(b.service?.name||b.providerName)}</td><td>${esc(b.destination)}</td><td>${money(b.amountMinor,b.currency)}</td><td>${b.status}</td></tr>`).join("")||emptyRow(6)}
async function loadSos(){const d=await req("/api/admin/sos");sosCards.innerHTML=d.alerts.map(a=>`<article class="sos-card ${a.status==="ACTIVE"?"active":""}"><div><span class="badge danger-badge">${a.status}</span><h3>${esc(a.user.name)}</h3><p>${esc(a.user.email)} · ${new Date(a.triggeredAt).toLocaleString()}</p><p>${esc(a.message||"No message")}</p>${a.latitude!=null?`<p>📍 ${a.latitude.toFixed(5)}, ${a.longitude.toFixed(5)}</p>`:"<p>📍 Location unavailable</p>"}</div>${a.status==="ACTIVE"?`<button class="btn danger" onclick="resolveSos('${a.id}')">Resolve</button>`:""}</article>`).join("")||"<p>No SOS alerts.</p>"}
async function resolveSos(id){try{await req("/api/admin/sos/"+id+"/resolve",{method:"POST",body:"{}"});loadStats();loadSos()}catch(e){alert(e.message)}}
function emptyRow(n){return `<tr><td colspan="${n}">No records found.</td></tr>`}function money(m,c="INR"){return new Intl.NumberFormat("en-IN",{style:"currency",currency:c,maximumFractionDigits:0}).format((m||0)/100)}function esc(x){return String(x??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]))}
const logout=document.querySelector("#logout");if(logout)logout.onclick=()=>{localStorage.removeItem("marg_admin_token");location.href="index.html"};