const API=localStorage.getItem("marg_api")||window.MARG_API_URL||"http://localhost:4000", token=()=>localStorage.getItem("marg_token");
async function get(path){const r=await fetch(API+path,{headers:{Authorization:"Bearer "+token()}});const d=await r.json();if(!r.ok)throw Error(d.error||"Request failed");return d}
async function post(path,body){const r=await fetch(API+path,{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+token()},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error||"Request failed");return d}
if(!token())location.href="traveller-login.html";
const icons={HOTEL:"🏨",ARTISAN:"🎨",FOOD:"🍲",TRANSPORT:"🚐",EXPERIENCE:"🌿",GUIDE:"🧭"};
let services=[];
async function init(){try{const me=await get("/api/me");if(me.user.role!=="TRAVELER")throw Error("Traveller account required");who.textContent=me.user.name;firstName.textContent=me.user.name.split(" ")[0];await loadServices();await loadBookings();await loadCompanions()}catch(e){alert(e.message);location.href="traveller-login.html"}}
async function loadServices(){const r=await fetch(API+"/api/services");const d=await r.json();services=d.services||[];renderServices("ALL")}
function renderServices(cat){const list=services.filter(s=>cat==="ALL"||s.category===cat);serviceGrid.innerHTML=list.map(s=>`<article class="service"><div class="service-cover">${icons[s.category]||"✨"}</div><div class="service-body"><span class="badge">${s.category}</span><h3>${esc(s.name)}</h3><p>${esc(s.description||"Local MARG service")}<br><b>${esc(s.destination)}</b><br>Service Provider: ${esc(s.provider?.name||"MARG service provider")}</p><div class="price">${money(s.priceMinor,s.currency)}</div><button class="btn primary" onclick="book('${s.id}')">Book service</button></div></article>`).join("")||"<p>No published services yet.</p>"}
document.querySelectorAll(".filters button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".filters button").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderServices(b.dataset.cat)});
async function book(id){const s=services.find(x=>x.id===id);const start=new Date();start.setDate(start.getDate()+1);try{await post("/api/bookings",{serviceId:id,startAt:start.toISOString(),guests:1});alert(`Booking created for ${s.name}`);loadBookings()}catch(e){alert(e.message)}}
async function loadBookings(){try{const d=await get("/api/bookings");bookingGrid.innerHTML=(d.bookings||[]).map(b=>`<div class="booking"><b>${esc(b.service?.name||b.providerName)}</b><br>${esc(b.destination)} · ${b.status}<br>${money(b.amountMinor,b.currency)}</div>`).join("")||"<p>No bookings yet.</p>"}catch(e){bookingGrid.innerHTML="<p>Could not load bookings.</p>"}}
generate.onclick=()=>{const d=destination.value,b=Number(budget.value)||0,n=Number(days.value)||3,i=interest.value,c=crowd.value;plan.innerHTML=`<h3>${n}-day ${esc(d)} plan · Budget ₹${b.toLocaleString("en-IN")}</h3>`+Array.from({length:n},(_,k)=>`<div class="plan-day"><b>Day ${k+1}</b> — ${esc(i)}. ${c}. Check MARG services in ${esc(d)} and keep spending within the trip budget.</div>`).join("")}
companionForm.onsubmit=async e=>{e.preventDefault();try{await post("/api/companions",{name:compName.value,relation:compRelation.value,phone:compPhone.value});compMsg.textContent="Companion saved.";e.target.reset();loadCompanions()}catch(x){compMsg.textContent=x.message}}
async function loadCompanions(){try{const d=await get("/api/companions");companionList.innerHTML=(d.companions||[]).map(c=>`<div class="companion"><span><b>${esc(c.name)}</b><br>${esc(c.relation||"Companion")}</span><span>${esc(c.phone)}</span></div>`).join("")||"<p>No companions added.</p>"}catch(e){}}
sos.onclick=async()=>{if(!confirm("Send an SOS alert to the MARG backend?"))return;const send=async p=>post("/api/sos",p);if(navigator.geolocation){navigator.geolocation.getCurrentPosition(async pos=>{try{await send({latitude:pos.coords.latitude,longitude:pos.coords.longitude,message:"Traveller SOS requested from MARG."});sosMsg.textContent="SOS alert recorded with your location."}catch(e){sosMsg.textContent=e.message}},async()=>{try{await send({message:"Traveller SOS requested from MARG; location unavailable."});sosMsg.textContent="SOS alert recorded without location."}catch(e){sosMsg.textContent=e.message}})}else{try{await send({message:"Traveller SOS requested from MARG; geolocation unavailable."});sosMsg.textContent="SOS alert recorded."}catch(e){sosMsg.textContent=e.message}}}
logout.onclick=()=>{localStorage.removeItem("marg_token");location.href="index.html"};
function money(m,c="INR"){return new Intl.NumberFormat("en-IN",{style:"currency",currency:c,maximumFractionDigits:0}).format((m||0)/100)}function esc(x){return String(x??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]))}
init();